//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWNovel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HWN03
    {
        public string NOVELID { get; set; }
        public string NOVELTITLE { get; set; }
        public string NOVELINFO { get; set; }
        public string WRITER { get; set; }
        public string GENRE { get; set; }
        public string THUMNAIL { get; set; }
        public string ENDYN { get; set; }
        public string MON { get; set; }
        public string TUE { get; set; }
        public string WED { get; set; }
        public string THU { get; set; }
        public string FRI { get; set; }
        public string SAT { get; set; }
        public string SUN { get; set; }
        public System.DateTime INSERTDT { get; set; }
    }
}
